namespace ChroniclesUnbound.Core;

/// <summary>
/// Describes what a character gains when leveling up. Generated by LevelUpManager.GetLevelUpInfo()
/// based on the character's class and the level they are advancing to.
/// </summary>
public class LevelUpInfo
{
    /// <summary>
    /// The level the character is advancing to.
    /// </summary>
    public int NewLevel { get; set; }

    /// <summary>
    /// The hit die size for HP rolls (e.g. 10 for a d10 class like Fighter).
    /// </summary>
    public int HPRollDie { get; set; }

    /// <summary>
    /// Class and subclass features gained at this level.
    /// </summary>
    public List<string> NewFeatures { get; set; } = new();

    /// <summary>
    /// True if this level grants an Ability Score Improvement (or feat choice).
    /// </summary>
    public bool HasASI { get; set; }

    /// <summary>
    /// New maximum spell slots indexed 0-8 for spell levels 1-9,
    /// or null if the class has no spellcasting at this level.
    /// </summary>
    public int[]? NewSpellSlots { get; set; }

    /// <summary>
    /// True if the character can learn or prepare new spells at this level.
    /// </summary>
    public bool CanLearnNewSpells { get; set; }

    /// <summary>
    /// Number of new spells the character can add (for known-spell casters like Bard/Sorcerer/Ranger/Warlock).
    /// For prepared casters (Cleric/Druid/Paladin/Wizard), this is 0 since they choose daily.
    /// </summary>
    public int NewSpellsCount { get; set; }

    /// <summary>
    /// True if this level requires a subclass choice (e.g. level 3 for most classes).
    /// </summary>
    public bool SubclassChoice { get; set; }

    /// <summary>
    /// True if the proficiency bonus changes at this level (levels 5, 9, 13, 17).
    /// </summary>
    public bool ProficiencyBonusChanged { get; set; }

    /// <summary>
    /// The proficiency bonus at the new level.
    /// </summary>
    public int NewProficiencyBonus { get; set; }
}
