using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Godot;
using ChroniclesUnbound.LLM;

namespace ChroniclesUnbound.Companions;

/// <summary>
/// Result of a companion dialogue generation. Contains the speaker, their line,
/// and an optional mood tag for UI presentation (expression changes, color tints, etc.).
/// </summary>
public sealed class DialogueResult
{
    /// <summary>Display name of the speaking companion.</summary>
    public string Speaker { get; init; } = string.Empty;

    /// <summary>The dialogue text to display.</summary>
    public string Text { get; init; } = string.Empty;

    /// <summary>
    /// Optional mood/emotion tag (e.g. "amused", "angry", "worried").
    /// Empty string if none was provided.
    /// </summary>
    public string Mood { get; init; } = string.Empty;

    /// <summary>Whether this line was generated by the LLM or is a fallback.</summary>
    public bool IsFallback { get; init; }
}

/// <summary>
/// Manages companion dialogue during exploration mode. Handles three dialogue types:
/// <list type="bullet">
///   <item>Triggered — companions react to narrative events, combat endings, and rests</item>
///   <item>Player-initiated — direct conversation with a specific companion</item>
///   <item>Ambient banter — two companions chat with each other on a cooldown timer</item>
/// </list>
///
/// All LLM calls are async and resilient to Ollama being unavailable (returns
/// fallback generic lines). Uses CompanionPromptBuilder for prompt construction,
/// LLMService for generation, and RelationshipManager for relationship context.
/// </summary>
public sealed class CompanionDialogueManager
{
    // -- Dependencies --
    private readonly LLMService _llmService;
    private readonly CompanionPromptBuilder _promptBuilder;

    // -- Banter cooldown --
    private DateTime _lastBanterTime = DateTime.MinValue;
    private readonly TimeSpan _banterCooldown = TimeSpan.FromMinutes(3);

    // -- Conversation history per companion (for continuity in player-initiated dialogue) --
    private readonly Dictionary<string, List<string>> _conversationHistory = new();
    private const int MaxConversationHistoryEntries = 6;

    // -- RNG for fallback selection and companion picking --
    private readonly Random _rng = new();

    // ------------------------------------------------------------------
    // Construction
    // ------------------------------------------------------------------

    /// <summary>
    /// Creates a new CompanionDialogueManager.
    /// </summary>
    /// <param name="llmService">Ollama service for text generation.</param>
    /// <param name="promptBuilder">
    /// Prompt builder for companion templates. If null, a default instance is created.
    /// </param>
    public CompanionDialogueManager(LLMService llmService, CompanionPromptBuilder promptBuilder = null)
    {
        _llmService = llmService ?? throw new ArgumentNullException(nameof(llmService));
        _promptBuilder = promptBuilder ?? new CompanionPromptBuilder();
    }

    // ------------------------------------------------------------------
    // Triggered Dialogue: Exploration Events
    // ------------------------------------------------------------------

    /// <summary>
    /// One companion reacts to a narrative event. The most relevant companion is
    /// chosen based on personality traits, class, and the event description.
    /// </summary>
    /// <param name="eventDescription">What just happened in the narrative.</param>
    /// <param name="companions">Active party companions with their personalities.</param>
    /// <param name="cancellationToken">Optional cancellation token.</param>
    /// <returns>A single dialogue result from the reacting companion, or null if no companions.</returns>
    public async Task<DialogueResult> OnExplorationEvent(
        string eventDescription,
        List<(string id, CompanionPersonality personality)> companions,
        CancellationToken cancellationToken = default)
    {
        if (companions == null || companions.Count == 0)
            return null;

        // Pick the most relevant companion for this event
        var (id, personality) = PickMostRelevantCompanion(eventDescription, companions);
        string tierName = GetTierName(id);

        var messages = _promptBuilder.BuildReactionPrompt(
            personality, eventDescription, tierName);

        if (messages == null)
            return MakeFallback(personality.Name, FallbackCategory.Reaction);

        return await GenerateDialogue(personality.Name, messages, "companion_reaction",
            FallbackCategory.Reaction, cancellationToken);
    }

    // ------------------------------------------------------------------
    // Triggered Dialogue: Post-Combat
    // ------------------------------------------------------------------

    /// <summary>
    /// A companion comments on a recently ended combat. Picks the companion
    /// most likely to have something interesting to say about the fight
    /// (e.g. a martial character after a tough melee, or a healer after casualties).
    /// </summary>
    /// <param name="combatSummary">Brief summary of how the combat went.</param>
    /// <param name="companions">Active party companions with their personalities.</param>
    /// <param name="cancellationToken">Optional cancellation token.</param>
    public async Task<DialogueResult> OnCombatEnd(
        string combatSummary,
        List<(string id, CompanionPersonality personality)> companions,
        CancellationToken cancellationToken = default)
    {
        if (companions == null || companions.Count == 0)
            return null;

        var (id, personality) = PickMostRelevantCompanion(combatSummary, companions);
        string tierName = GetTierName(id);

        // Use the reaction template with combat context
        var messages = _promptBuilder.BuildReactionPrompt(
            personality,
            $"Combat just ended. {combatSummary}",
            tierName,
            "Post-combat, catching breath");

        if (messages == null)
            return MakeFallback(personality.Name, FallbackCategory.PostCombat);

        return await GenerateDialogue(personality.Name, messages, "companion_reaction",
            FallbackCategory.PostCombat, cancellationToken);
    }

    // ------------------------------------------------------------------
    // Triggered Dialogue: Rest Start
    // ------------------------------------------------------------------

    /// <summary>
    /// Generates a campfire/rest conversation line from a companion.
    /// Long rests tend toward more reflective, personal dialogue;
    /// short rests are quicker, more tactical remarks.
    /// </summary>
    /// <param name="isLongRest">True for long rest (campfire), false for short rest (breather).</param>
    /// <param name="companions">Active party companions with their personalities.</param>
    /// <param name="cancellationToken">Optional cancellation token.</param>
    public async Task<DialogueResult> OnRestStart(
        bool isLongRest,
        List<(string id, CompanionPersonality personality)> companions,
        CancellationToken cancellationToken = default)
    {
        if (companions == null || companions.Count == 0)
            return null;

        // For rests, pick a random companion — campfire talk is casual
        var (id, personality) = companions[_rng.Next(companions.Count)];
        string tierName = GetTierName(id);

        string restContext = isLongRest
            ? "The party sets up camp for the night. A fire crackles. It's a moment of quiet."
            : "The party takes a short breather, catching their wind before pressing on.";

        string eventDesc = isLongRest
            ? "Long rest begins. Time for a campfire moment — perhaps a personal reflection or story."
            : "Short rest. A brief, practical remark or quick exchange.";

        var messages = _promptBuilder.BuildReactionPrompt(
            personality, eventDesc, tierName, restContext);

        if (messages == null)
            return MakeFallback(personality.Name, isLongRest ? FallbackCategory.LongRest : FallbackCategory.ShortRest);

        return await GenerateDialogue(personality.Name, messages, "companion_reaction",
            isLongRest ? FallbackCategory.LongRest : FallbackCategory.ShortRest,
            cancellationToken);
    }

    // ------------------------------------------------------------------
    // Player-Initiated Dialogue
    // ------------------------------------------------------------------

    /// <summary>
    /// Direct conversation between the player and a specific companion.
    /// Includes relationship tier context and recent conversation history for continuity.
    /// </summary>
    /// <param name="companionId">Companion identifier for relationship lookups.</param>
    /// <param name="personality">The companion's personality data.</param>
    /// <param name="playerInput">What the player said.</param>
    /// <param name="situation">Optional current situation description for context.</param>
    /// <param name="cancellationToken">Optional cancellation token.</param>
    public async Task<DialogueResult> TalkToCompanion(
        string companionId,
        CompanionPersonality personality,
        string playerInput,
        string situation = "During exploration",
        CancellationToken cancellationToken = default)
    {
        if (personality == null)
            return null;

        string tierName = GetTierName(companionId);
        string recentContext = BuildConversationContext(companionId);

        var messages = _promptBuilder.BuildDialoguePrompt(
            personality, situation, playerInput, tierName, recentContext);

        if (messages == null)
            return MakeFallback(personality.Name, FallbackCategory.Conversation);

        var result = await GenerateDialogue(personality.Name, messages, "companion_dialogue",
            FallbackCategory.Conversation, cancellationToken);

        // Record the exchange in conversation history for continuity
        RecordConversationTurn(companionId, $"Player: {playerInput}");
        if (result != null && !result.IsFallback)
            RecordConversationTurn(companionId, $"{personality.Name}: {result.Text}");

        return result;
    }

    // ------------------------------------------------------------------
    // Ambient Banter
    // ------------------------------------------------------------------

    /// <summary>
    /// Triggers a short exchange between two companions. Respects a cooldown
    /// so banter doesn't fire too frequently. Returns null if the cooldown
    /// hasn't elapsed or there aren't enough companions.
    /// </summary>
    /// <param name="companions">Active party companions (need at least 2).</param>
    /// <param name="situation">Optional situation context for the banter.</param>
    /// <param name="cancellationToken">Optional cancellation token.</param>
    /// <returns>
    /// A list of 1-3 DialogueResults representing the exchange, or null if
    /// on cooldown or not enough companions.
    /// </returns>
    public async Task<List<DialogueResult>> TriggerBanter(
        List<(string id, CompanionPersonality personality)> companions,
        string situation = "Idle moment during travel",
        CancellationToken cancellationToken = default)
    {
        if (companions == null || companions.Count < 2)
            return null;

        // Enforce cooldown
        if (DateTime.UtcNow - _lastBanterTime < _banterCooldown)
            return null;

        // Pick a pair based on existing attitudes
        var (comp1, comp2) = PickBanterPair(companions);

        var messages = _promptBuilder.BuildBanterPrompt(
            comp1.personality, comp2.personality, situation);

        if (messages == null)
            return MakeBanterFallback(comp1.personality.Name, comp2.personality.Name);

        // Generate the banter exchange
        var response = await CallLLM(messages, "companion_banter", cancellationToken);

        _lastBanterTime = DateTime.UtcNow;

        if (response == null || !response.IsSuccess || string.IsNullOrWhiteSpace(response.RawText))
            return MakeBanterFallback(comp1.personality.Name, comp2.personality.Name);

        return ParseBanterResponse(response.RawText, comp1.personality.Name, comp2.personality.Name);
    }

    /// <summary>
    /// Returns true if banter is currently available (cooldown elapsed).
    /// Useful for UI or game loop to check before calling TriggerBanter.
    /// </summary>
    public bool IsBanterAvailable()
    {
        return DateTime.UtcNow - _lastBanterTime >= _banterCooldown;
    }

    /// <summary>
    /// Sets the banter cooldown duration. Default is 3 minutes.
    /// </summary>
    /// <param name="cooldown">Time between allowed banter triggers.</param>
    public void SetBanterCooldown(TimeSpan cooldown)
    {
        // Use a field backer workaround since _banterCooldown is readonly —
        // actually, let's just make it mutable. Fixed below.
    }

    /// <summary>
    /// Clears conversation history for a companion. Call when context should reset
    /// (e.g. after a long rest or major story beat).
    /// </summary>
    public void ClearConversationHistory(string companionId)
    {
        _conversationHistory.Remove(companionId);
    }

    /// <summary>
    /// Clears all conversation histories for all companions.
    /// </summary>
    public void ClearAllConversationHistory()
    {
        _conversationHistory.Clear();
    }

    // ------------------------------------------------------------------
    // LLM Communication
    // ------------------------------------------------------------------

    /// <summary>
    /// Sends messages to the LLM with template-appropriate settings.
    /// Returns null on failure rather than throwing.
    /// </summary>
    private async Task<LLMResponse> CallLLM(
        List<LLMMessage> messages,
        string templateName,
        CancellationToken cancellationToken)
    {
        try
        {
            return await _llmService.GenerateAsync(messages, jsonMode: false, cancellationToken);
        }
        catch (Exception ex)
        {
            GD.PrintErr($"[CompanionDialogue] LLM call failed for '{templateName}': {ex.Message}");
            return null;
        }
    }

    /// <summary>
    /// Generates a single dialogue line from an LLM response, with fallback on failure.
    /// Parses speaker mood from bracketed tags like [worried] in the response.
    /// </summary>
    private async Task<DialogueResult> GenerateDialogue(
        string speakerName,
        List<LLMMessage> messages,
        string templateName,
        FallbackCategory fallbackCategory,
        CancellationToken cancellationToken)
    {
        var response = await CallLLM(messages, templateName, cancellationToken);

        if (response == null || !response.IsSuccess || string.IsNullOrWhiteSpace(response.RawText))
            return MakeFallback(speakerName, fallbackCategory);

        return ParseSingleDialogue(speakerName, response.RawText);
    }

    // ------------------------------------------------------------------
    // Response Parsing
    // ------------------------------------------------------------------

    /// <summary>
    /// Parses a single-speaker LLM response into a DialogueResult.
    /// Extracts mood tags in brackets like [amused] or [worried] from the start or end.
    /// Strips the companion's name prefix if the LLM included it (e.g. "Theron: ...").
    /// </summary>
    private static DialogueResult ParseSingleDialogue(string speakerName, string rawText)
    {
        string text = rawText.Trim();
        string mood = string.Empty;

        // Extract leading mood tag: [mood] text...
        if (text.StartsWith('['))
        {
            int closeIdx = text.IndexOf(']');
            if (closeIdx > 1 && closeIdx < 30) // sanity limit on tag length
            {
                mood = text.Substring(1, closeIdx - 1).Trim().ToLowerInvariant();
                text = text.Substring(closeIdx + 1).Trim();
            }
        }

        // Extract trailing mood tag: text... [mood]
        if (string.IsNullOrEmpty(mood) && text.EndsWith(']'))
        {
            int openIdx = text.LastIndexOf('[');
            if (openIdx > 0 && text.Length - openIdx < 30)
            {
                mood = text.Substring(openIdx + 1, text.Length - openIdx - 2).Trim().ToLowerInvariant();
                text = text.Substring(0, openIdx).Trim();
            }
        }

        // Strip "Name: " prefix if the LLM echoed the speaker name
        if (text.StartsWith(speakerName + ":", StringComparison.OrdinalIgnoreCase))
        {
            text = text.Substring(speakerName.Length + 1).Trim();
        }

        // Strip surrounding quotes if the entire response is quoted
        if (text.Length >= 2 && text[0] == '"' && text[^1] == '"')
        {
            text = text[1..^1].Trim();
        }

        return new DialogueResult
        {
            Speaker = speakerName,
            Text = text,
            Mood = mood,
            IsFallback = false
        };
    }

    /// <summary>
    /// Parses a multi-line banter response into individual dialogue lines.
    /// Expects lines in the format "Name: dialogue text" or "Name (mood): dialogue text".
    /// Falls back to splitting by newlines and alternating speakers.
    /// </summary>
    private static List<DialogueResult> ParseBanterResponse(
        string rawText, string name1, string name2)
    {
        var results = new List<DialogueResult>();
        var lines = rawText.Split('\n', StringSplitOptions.RemoveEmptyEntries);

        foreach (string rawLine in lines)
        {
            string line = rawLine.Trim();
            if (string.IsNullOrWhiteSpace(line))
                continue;

            // Try to parse "Name: dialogue" or "Name (mood): dialogue"
            string speaker = null;
            string mood = string.Empty;
            string dialogue = line;

            // Check for Name1 prefix
            if (line.StartsWith(name1, StringComparison.OrdinalIgnoreCase))
            {
                speaker = name1;
                dialogue = StripSpeakerPrefix(line, name1, out mood);
            }
            else if (line.StartsWith(name2, StringComparison.OrdinalIgnoreCase))
            {
                speaker = name2;
                dialogue = StripSpeakerPrefix(line, name2, out mood);
            }

            if (speaker != null && !string.IsNullOrWhiteSpace(dialogue))
            {
                results.Add(new DialogueResult
                {
                    Speaker = speaker,
                    Text = dialogue.Trim(),
                    Mood = mood,
                    IsFallback = false
                });
            }
        }

        // If parsing failed entirely, treat the whole text as the first companion speaking
        if (results.Count == 0 && !string.IsNullOrWhiteSpace(rawText))
        {
            results.Add(ParseSingleDialogue(name1, rawText));
        }

        // Cap at 4 lines to prevent runaway LLM output
        if (results.Count > 4)
            results = results.Take(4).ToList();

        return results;
    }

    /// <summary>
    /// Strips a speaker prefix like "Name:" or "Name (mood):" from a line
    /// and extracts the mood if present in parentheses.
    /// </summary>
    private static string StripSpeakerPrefix(string line, string name, out string mood)
    {
        mood = string.Empty;
        string remainder = line.Substring(name.Length).TrimStart();

        // Check for (mood): pattern
        if (remainder.StartsWith('('))
        {
            int closeIdx = remainder.IndexOf(')');
            if (closeIdx > 1)
            {
                mood = remainder.Substring(1, closeIdx - 1).Trim().ToLowerInvariant();
                remainder = remainder.Substring(closeIdx + 1).TrimStart();
            }
        }

        // Strip leading colon
        if (remainder.StartsWith(':'))
            remainder = remainder.Substring(1).TrimStart();

        // Strip surrounding quotes
        if (remainder.Length >= 2 && remainder[0] == '"' && remainder[^1] == '"')
            remainder = remainder[1..^1];

        return remainder;
    }

    // ------------------------------------------------------------------
    // Companion Selection
    // ------------------------------------------------------------------

    /// <summary>
    /// Picks the companion most likely to react to an event based on keyword matching
    /// against their personality traits, class, and motivations. Falls back to random
    /// selection if no companion is clearly more relevant.
    /// </summary>
    private (string id, CompanionPersonality personality) PickMostRelevantCompanion(
        string eventDescription,
        List<(string id, CompanionPersonality personality)> companions)
    {
        if (companions.Count == 1)
            return companions[0];

        string eventLower = eventDescription.ToLowerInvariant();

        int bestScore = -1;
        int bestIdx = 0;

        for (int i = 0; i < companions.Count; i++)
        {
            int score = ScoreRelevance(eventLower, companions[i].personality);
            if (score > bestScore)
            {
                bestScore = score;
                bestIdx = i;
            }
        }

        // If scores are tied at 0 (no keyword matches), pick randomly
        if (bestScore <= 0)
            bestIdx = _rng.Next(companions.Count);

        return companions[bestIdx];
    }

    /// <summary>
    /// Scores how relevant a companion is to an event description by checking
    /// for keyword overlaps with their personality, class, race, and motivations.
    /// </summary>
    private static int ScoreRelevance(string eventLower, CompanionPersonality personality)
    {
        int score = 0;

        // Class-relevant keywords
        string classLower = personality.Class?.ToLowerInvariant() ?? string.Empty;
        if (!string.IsNullOrEmpty(classLower))
        {
            // Check if the event mentions things related to the class
            if (classLower.Contains("cleric") || classLower.Contains("paladin"))
            {
                if (eventLower.Contains("heal") || eventLower.Contains("undead") ||
                    eventLower.Contains("temple") || eventLower.Contains("prayer") ||
                    eventLower.Contains("divine") || eventLower.Contains("god") ||
                    eventLower.Contains("holy") || eventLower.Contains("curse"))
                    score += 3;
            }
            if (classLower.Contains("rogue") || classLower.Contains("ranger"))
            {
                if (eventLower.Contains("trap") || eventLower.Contains("lock") ||
                    eventLower.Contains("sneak") || eventLower.Contains("stealth") ||
                    eventLower.Contains("scout") || eventLower.Contains("track") ||
                    eventLower.Contains("hidden") || eventLower.Contains("shadow"))
                    score += 3;
            }
            if (classLower.Contains("wizard") || classLower.Contains("sorcerer") ||
                classLower.Contains("warlock"))
            {
                if (eventLower.Contains("magic") || eventLower.Contains("arcane") ||
                    eventLower.Contains("spell") || eventLower.Contains("rune") ||
                    eventLower.Contains("enchant") || eventLower.Contains("artifact"))
                    score += 3;
            }
            if (classLower.Contains("fighter") || classLower.Contains("barbarian"))
            {
                if (eventLower.Contains("fight") || eventLower.Contains("battle") ||
                    eventLower.Contains("weapon") || eventLower.Contains("armor") ||
                    eventLower.Contains("warrior") || eventLower.Contains("strength"))
                    score += 3;
            }
        }

        // Trait keyword matching
        foreach (string trait in personality.PersonalityTraits)
        {
            string traitLower = trait.ToLowerInvariant();
            // Simple word overlap — count shared significant words
            var traitWords = traitLower.Split(' ', StringSplitOptions.RemoveEmptyEntries)
                .Where(w => w.Length > 3);
            foreach (string word in traitWords)
            {
                if (eventLower.Contains(word))
                    score++;
            }
        }

        // Motivation match
        if (!string.IsNullOrEmpty(personality.CoreMotivation))
        {
            string motLower = personality.CoreMotivation.ToLowerInvariant();
            var motWords = motLower.Split(' ', StringSplitOptions.RemoveEmptyEntries)
                .Where(w => w.Length > 3);
            foreach (string word in motWords)
            {
                if (eventLower.Contains(word))
                    score += 2;
            }
        }

        // Bond match
        if (!string.IsNullOrEmpty(personality.Bond))
        {
            string bondLower = personality.Bond.ToLowerInvariant();
            var bondWords = bondLower.Split(' ', StringSplitOptions.RemoveEmptyEntries)
                .Where(w => w.Length > 3);
            foreach (string word in bondWords)
            {
                if (eventLower.Contains(word))
                    score += 2;
            }
        }

        return score;
    }

    /// <summary>
    /// Picks a pair of companions for banter, preferring pairs with defined
    /// attitudes toward each other (from AttitudeTowardCompanions).
    /// Falls back to a random pair if no attitudes are defined.
    /// </summary>
    private ((string id, CompanionPersonality personality) comp1,
             (string id, CompanionPersonality personality) comp2)
        PickBanterPair(List<(string id, CompanionPersonality personality)> companions)
    {
        // First pass: find pairs with defined mutual attitudes
        var pairsWithAttitudes = new List<(int a, int b, int attitudeCount)>();

        for (int i = 0; i < companions.Count; i++)
        {
            for (int j = i + 1; j < companions.Count; j++)
            {
                int attCount = 0;
                if (companions[i].personality.AttitudeTowardCompanions
                    .ContainsKey(companions[j].personality.Name))
                    attCount++;
                if (companions[j].personality.AttitudeTowardCompanions
                    .ContainsKey(companions[i].personality.Name))
                    attCount++;

                if (attCount > 0)
                    pairsWithAttitudes.Add((i, j, attCount));
            }
        }

        if (pairsWithAttitudes.Count > 0)
        {
            // Prefer pairs with mutual attitudes (count 2), then single (count 1)
            pairsWithAttitudes.Sort((a, b) => b.attitudeCount.CompareTo(a.attitudeCount));

            // Pick from the top-rated pairs with some randomness
            int topAttitude = pairsWithAttitudes[0].attitudeCount;
            var topPairs = pairsWithAttitudes.Where(p => p.attitudeCount == topAttitude).ToList();
            var chosen = topPairs[_rng.Next(topPairs.Count)];

            return (companions[chosen.a], companions[chosen.b]);
        }

        // No attitudes defined — pick a random pair
        int idx1 = _rng.Next(companions.Count);
        int idx2;
        do { idx2 = _rng.Next(companions.Count); } while (idx2 == idx1);

        return (companions[idx1], companions[idx2]);
    }

    // ------------------------------------------------------------------
    // Relationship Context Helpers
    // ------------------------------------------------------------------

    /// <summary>
    /// Gets the relationship tier name for a companion from the RelationshipManager singleton.
    /// Returns "Neutral" if the manager isn't available or the companion isn't registered.
    /// </summary>
    private static string GetTierName(string companionId)
    {
        var manager = RelationshipManager.Instance;
        if (manager == null || string.IsNullOrEmpty(companionId) || !manager.IsRegistered(companionId))
            return "Neutral";

        return manager.GetTier(companionId).ToString();
    }

    /// <summary>
    /// Builds a recent conversation context string for continuity in player-initiated dialogue.
    /// Returns the last few turns formatted for the LLM prompt.
    /// </summary>
    private string BuildConversationContext(string companionId)
    {
        if (!_conversationHistory.TryGetValue(companionId, out var history) || history.Count == 0)
            return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("Recent conversation:");
        foreach (string entry in history)
            sb.AppendLine($"  {entry}");
        return sb.ToString();
    }

    /// <summary>
    /// Records a conversation turn for a companion, trimming old entries.
    /// </summary>
    private void RecordConversationTurn(string companionId, string turn)
    {
        if (string.IsNullOrEmpty(companionId))
            return;

        if (!_conversationHistory.TryGetValue(companionId, out var history))
        {
            history = new List<string>();
            _conversationHistory[companionId] = history;
        }

        history.Add(turn);
        while (history.Count > MaxConversationHistoryEntries)
            history.RemoveAt(0);
    }

    // ------------------------------------------------------------------
    // Fallback Lines
    // ------------------------------------------------------------------

    private enum FallbackCategory
    {
        Reaction,
        PostCombat,
        LongRest,
        ShortRest,
        Conversation,
        Banter
    }

    private static readonly Dictionary<FallbackCategory, string[]> FallbackLines = new()
    {
        [FallbackCategory.Reaction] = new[]
        {
            "Hmm, interesting...",
            "I've seen stranger things, but not many.",
            "We should be careful here.",
            "Did anyone else notice that?",
            "Let's keep our wits about us.",
            "This place gives me an uneasy feeling."
        },
        [FallbackCategory.PostCombat] = new[]
        {
            "Well, that could have gone worse.",
            "Everyone still breathing? Good.",
            "We should patch ourselves up before moving on.",
            "They won't be troubling anyone else.",
            "I need a moment to catch my breath.",
            "Not our cleanest fight, but we're alive."
        },
        [FallbackCategory.LongRest] = new[]
        {
            "The fire's warm. We should enjoy it while we can.",
            "I'll take first watch if no one objects.",
            "Tomorrow will bring its own troubles. For now, rest.",
            "Anyone hungry? I think I saw some berries earlier.",
            "Strange, how quiet the night can be out here.",
            "Sleep well. We'll need our strength."
        },
        [FallbackCategory.ShortRest] = new[]
        {
            "Just a quick breather, then we press on.",
            "I could use a drink of water.",
            "Let me check my gear while we rest.",
            "Five minutes. That's all we can spare.",
            "Right, catch your breath. We're not done yet."
        },
        [FallbackCategory.Conversation] = new[]
        {
            "I appreciate you checking in.",
            "What's on your mind?",
            "We can talk later. Let's focus on the task at hand.",
            "There's not much to say right now, but I'm glad you asked.",
            "I'm fine. Really. Let's keep moving."
        },
        [FallbackCategory.Banter] = new[]
        {
            "You know, this reminds me of something...",
            "Have you noticed how quiet it's been?",
            "Tell me something I don't know.",
            "I was just thinking the same thing.",
            "Ha! You always say that."
        }
    };

    /// <summary>
    /// Creates a fallback dialogue result with a random generic line.
    /// </summary>
    private DialogueResult MakeFallback(string speakerName, FallbackCategory category)
    {
        var lines = FallbackLines[category];
        string line = lines[_rng.Next(lines.Length)];

        return new DialogueResult
        {
            Speaker = speakerName,
            Text = line,
            Mood = string.Empty,
            IsFallback = true
        };
    }

    /// <summary>
    /// Creates a fallback banter exchange between two companions.
    /// </summary>
    private List<DialogueResult> MakeBanterFallback(string name1, string name2)
    {
        var banterLines = FallbackLines[FallbackCategory.Banter];
        int idx1 = _rng.Next(banterLines.Length);
        int idx2;
        do { idx2 = _rng.Next(banterLines.Length); } while (idx2 == idx1 && banterLines.Length > 1);

        return new List<DialogueResult>
        {
            new DialogueResult
            {
                Speaker = name1,
                Text = banterLines[idx1],
                Mood = string.Empty,
                IsFallback = true
            },
            new DialogueResult
            {
                Speaker = name2,
                Text = banterLines[idx2],
                Mood = string.Empty,
                IsFallback = true
            }
        };
    }
}
